#!/bin/sh

uci add firewall rule
uci set firewall.@rule[-1].name='block-dot-wan'
uci set firewall.@rule[-1].src='*'
uci set firewall.@rule[-1].dest='wan'
uci set firewall.@rule[-1].dest_port='853'
uci set firewall.@rule[-1].target='REJECT'

uci add firewall rule
uci set firewall.@rule[-1].name='block-dot-wgclient'
uci set firewall.@rule[-1].src='*'
uci set firewall.@rule[-1].dest='wgclient'
uci set firewall.@rule[-1].dest_port='853'
uci set firewall.@rule[-1].target='REJECT'

uci add firewall redirect
uci set firewall.@redirect[-1].name='hijack-dns'
uci set firewall.@redirect[-1].src='*'
uci set firewall.@redirect[-1].src_dport='53'
uci set firewall.@redirect[-1].target='DNAT'

# if banip doesn't work for some reason, lets add some route blackhole rules to ensure sneaky google cannot use dns via doh :)
uci add network rule
uci set network.@rule[-1].action='blackhole'
uci set network.@rule[-1].dest='1.1.1.1/32'
uci set network.@rule[-1].lookup='main'

uci add network rule
uci set network.@rule[-1].action='blackhole'
uci set network.@rule[-1].dest='1.1.1.2/32'
uci set network.@rule[-1].lookup='main'


uci add network rule
uci set network.@rule[-1].action='blackhole'
uci set network.@rule[-1].dest='1.1.1.3/32'
uci set network.@rule[-1].lookup='main'

uci add network rule
uci set network.@rule[-1].action='blackhole'
uci set network.@rule[-1].dest='8.8.8.8/32'
uci set network.@rule[-1].lookup='main'

uci add network rule
uci set network.@rule[-1].action='blackhole'
uci set network.@rule[-1].dest='8.8.4.4/32'
uci set network.@rule[-1].lookup='main'

uci commit firewall
uci commit network

exit 0