#!/bin/sh

if [ "$(uci -q get xsdk.@factory[0].enabled)" != "1" ];
then
	uci del_list network.@device[0].ports='sfp'
	uci add_list network.@device[0].ports='wan'
	uci set network.wan.device='sfp.300'
	uci commit network
fi

exit 0

