#!/bin/sh

if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then

uci batch << EOI

set ghn.ghn=ghn
set ghn.ghn.disabled=1
set ghn.ghn.interface=ghn
set ghn.settings=settings
set ghn.settings.device_name="insertname"
set ghn.settings.domain_name="yourdomain"
set ghn.settings.password="password"
set ghn.settings.pairing_secured=1
set ghn.settings.pairing_completed=1
set ghn.settings.powermask_profile=mimo_full
set ghn.settings.dslcoex_enable=0
set ghn.settings.force_node=0
set ghn.ghn.device_name_initialized=1

EOI

uci commit ghn

/etc/init.d/ghn-host enable

fi

exit 0

