#!/bin/sh
if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ];
then
	uci set network.@device[0].bridge_empty='1'


        #lan1 = wan
	#lan2 = lan


	uci del_list network.@device[0].ports='lan1'
	uci add network device
	uci set network.@device[-1].name='br-wan'
	uci set network.@device[-1].type='bridge'
	uci add_list network.@device[-1].ports='lan1'
	uci add_list network.@device[-1].ports='ghn'
	uci add_list network.@device[-1].bridge_empty='1'

	uci set network.wan.device='br-wan'
	uci set network.wan.classlessroute='0'

	uci commit network
	
fi

exit 0

