#!/bin/sh
if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then

    uci set firewall.@zone[1].input='ACCEPT'
    uci set firewall.@zone[1].forward='ACCEPT'
    uci set firewall.@defaults[0].input='ACCEPT'
    uci set firewall.@defaults[0].output='ACCEPT'
    uci set firewall.@defaults[0].forward='ACCEPT'

    uci commit firewall
fi

exit 0

