#!/bin/sh

if [ $(uci -q get banip.global.ban_allowflag) != '4443 4445']
then
	uci add_list banip.global.ban_blockforwardlan='doh'
	uci set banip.global.ban_allowflag='4443 4445'
	uci commit banip
fi

exit 0